name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
         description: select tests to run
         required: true
         type: choice
         default: all
         options:
           - all
jobs:
   runs-tests:
     runs-on: windows
     name: Tests
     steps: 
        - name: copy source code
        - uses: actions/checkout@v4
        - name: set up python env
        - uses: actions/setup-python@v5
          with:
             python-version: "3.12"
        - name:  install dependencies
          run: pip install requirements.txt
        - name: Run tests
          run: Pytest -v 
     
